import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import Navbar from '../components/Navbar';
import './globals.css';

const inter = Public_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`w-full h-min-screen flex bg-beige-100 ${inter.className}`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
